name: "local-action"
description: Grading action for local exercise
author: githubtraining

runs:
  using: node12
  main: "dist/index.js"
- uses: github/codeql-action/init@v3
  with:
    config-file: ./.github/codeql/codeql-config.yml
